### ISSUE TITLE
抓到动态后无法向cq-http推送内容

### ISSUE THREAD

**Issue by b1xcy** [MountainDash/nonebot-bison#340]
## 环境

- nonebot-bison 版本：0.8.0
- nonebot 版本：1.2.2
- 安装方式：（以下方式的一种或者其他方式）
使用docker-compose配置
- 操作系统：
CentOS 7.9
## 问题

在抓取到b站新动态后，不向cq-http推送。使用docker logs查看cq-http的日志，也没有推送的日志

## 日志

```
08-10 12:00:45 [INFO] nonebot_bison | fetch new post from bilibili 690608690: 828076583805780039
08-10 12:00:45 [WARNING] nonebot_bison | API request record: **
08-10 12:00:45 [ERROR] logging | Job "Scheduler.exec_fetch (trigger: interval[0:00:10], next run at: 2023-08-10 12:00:54 CST)" raised an exception
Traceback (most recent call last):
  File "/app/bot.py", line 18, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.11/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
> File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/app/nonebot_bison/scheduler/scheduler.py", line 79, in exec_fetch
    to_send = await platform_obj.do_fetch_new_post(schedulable.target, send_userinfo_list)
  File "/app/nonebot_bison/platform/platform.py", line 92, in do_fetch_new_post
    return await self.fetch_new_post(target, users)
  File "/app/nonebot_bison/platform/platform.py", line 315, in fetch_new_post
    res = await self.dispatch_user_post(target, new_posts, users)
  File "/app/nonebot_bison/platform/platform.py", line 200, in dispatch_user_post
    user_post.append(await self.do_parse(raw_post))
  File "/app/nonebot_bison/platform/platform.py", line 232, in do_parse
    raise err
  File "/app/nonebot_bison/platform/platform.py", line 227, in do_parse
    self.parse_cache[post_id] = await self.parse(raw_post)
  File "/app/nonebot_bison/platform/bilibili.py", line 180, in parse
    text, pic = self._get_info(post_type, card_content)
  File "/app/nonebot_bison/platform/bilibili.py", line 143, in _get_info
    if text_similarity(desc, dynamic) > 0.8:
  File "/app/nonebot_bison/utils/__init__.py", line 100, in text_similarity
    return t / min(len(str1), len(str2))
ZeroDivisionError: ('division by zero', [**])
```

- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
这个问题已经修了 不过pr还没合 #302 
不过 nonebot 1.2.2 这个版本是真的吗

**Comment by b1xcy** [comment]
> 这个问题已经修了 不过pr还没合 #302 不过 nonebot 1.2.2 这个版本是真的吗

草，搞错了 应该是go-cqhttp 1.1.0

**Comment by AzideCupric** [comment]
文本除0报错 #302 已合并，可以看看是否符合预期
