### ISSUE TITLE
0.9.0docker-compose部署报错:'allow_population_by_field_name' has been renamed to 'populate_by_name'

### ISSUE THREAD

**Issue by b1xcy** [MountainDash/nonebot-bison#493]
## 环境

- nonebot-bison 版本：v0.9.0
- nonebot 版本：
- 安装方式：（以下方式的一种或者其他方式）
 通过docker-compose部署
- 操作系统：

## 问题

使用docker-compose up启动时报错：`'allow_population_by_field_name' has been renamed to 'populate_by_name'`

## 日志

```
sudo docker-compose run nonebot
Starting go-cqhttp ... done
Creating qbot_nonebot_run ... done
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
03-05 14:12:04 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/local/lib/python3.11/site-packages/nonebot/__init__.py", line 298, in init
    config = Config(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nonebot/config.py", line 343, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
superusers.0
  Input should be a valid string [type=string_type, input_value="admin", input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type

```

- [√] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [√] 我确认在日志中去掉了敏感信息

**Comment by he0119** [comment]
请问你 superusers 填写的什么？这个报错的意思是你填写的类型不是 str。

**Comment by b1xcy** [comment]
在之前的版本中，我在docker-compose.yml中指定`SUPERUSERS: '[admin]'`
升级到0.9.0后需要修改为`SUPERUSERS: '["admin"]'`
与此同时数据库中存储的数据类型同样不兼容，需要删库（

**Comment by he0119** [comment]
后台管理有 bug <https://github.com/MountainDash/nonebot-bison/pull/486>，请等待新版发布。

**Comment by felinae98** [comment]
试试 0.9.1

**Comment by b1xcy** [comment]
0.9.1没问题了
