### ISSUE TITLE
新版本提示AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])

### ISSUE THREAD

**Issue by Nenot233** [MountainDash/nonebot-bison#539]
## 环境

- nonebot-bison 版本：fix/bilibili-dyn
- nonebot 版本：2.2.1
- 安装方式：（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装

- 操作系统：WIN10

## 问题

显示报错("'NoneType' object has no attribute 'get_live_action'", [])

## 日志

```

05-04 20:11:20 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:15], next run at: 2024-05-04 20:11:35 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
 File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 107, in exec_fetch
    to_send = await platform_obj.do_fetch_new_post(SubUnit(schedulable.target, send_userinfo_list))
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 109, in do_fetch_new_post
    return await catch_network_error(self.fetch_new_post, sub_unit) or []
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 53, in catch_network_error
    return await func(*args, **kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 396, in fetch_new_post
    return await self._handle_status_change(new_status, sub_unit)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 376, in _handle_status_change
    diff = self.compare_status(sub_unit.sub_target, old_status, new_status)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\bilibili\platforms.py", line 443, in compare_status
    match new_status.get_live_action(old_status):
AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])
```

- [√] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [√] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
可以的话能不能提供一下关注的主播？

**Comment by Nenot233** [comment]
UID:690608698
B站 订阅分类:专栏文章、一般动态、视频、文字、转发、直播推送

**Comment by Nenot233** [comment]
以及新的2个报错log，导致直播无法推送，服务器规则代理日本
```05-14 08:16:14 [WARNING] nonebot_bison | API request record: https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids%5B%5D=1827139579&uids%5B%5D=666726799&uids%5B%5D=14950589&uids%5B%5D=1873291&uids%5B%5D=690608698&uids%5B%5D=477317922&uids%5B%5D=1464029182&uids%5B%5D=14387072&uids%5B%5D=1542516095&uids%5B%5D=1762745&uids%5B%5D=2039332008&uids%5B%5D=617459493&uids%5B%5D=863287&uids%5B%5D=594827452&uids%5B%5D=1950658&uids%5B%5D=56748733&uids%5B%5D=731556&uids%5B%5D=23269266&uids%5B%5D=1873291%20 Headers({'host': 'api.live.bilibili.com', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'cookie':  [200] Headers({'date': 'Tue, 14 May 2024 00:16:14 GMT', 'content-type': 'application/json', 'content-length': '143', 'connection': 'keep-alive', 'bili-status-code': '65530', 'bili-trace-id': '64cb2cb9a513a3e90ada9038056642ad:17cf32bde09505fd:ada9038056642ad:0', 'cache-control': 'no-cache', 'server': 'swoole-http-server', 'x-bili-trace-id': '64cb2cb9a513a3e90ada9038056642ad:17cf32bde09505fd:ada9038056642ad:0', 'x-envoy-upstream-service-time': '0', 'vary': 'Accept-Encoding,Origin', 'expires': 'Tue, 14 May 2024 00:16:13 GMT', 'x-cache-webcdn': 'BYPASS from blzone06'}) {"code":65530,"msg":"route_exception","message":"route_exception","data":{"excp_code":0,"excp_msg":"Expect integer.","excp_class":"Exception"}}
05-14 08:16:14 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:15], next run at: 2024-05-14 08:16:28 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 102, in exec_fetch
    to_send = await platform_obj.do_batch_fetch_new_post(sub_units)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 115, in do_batch_fetch_new_post
    return await catch_network_error(self.batch_fetch_new_post, sub_units) or []
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 53, in catch_network_error
    return await func(*args, **kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 401, in batch_fetch_new_post
    new_statuses = await self.batch_get_status([x[0] for x in sub_units])
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\bilibili\platforms.py", line 430, in batch_get_status
    raise self.FetchError()
nonebot_bison.platform.platform.StatusChange.FetchError: ['https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids%5B%5D=1827139579&uids%5B%5D=666726799&uids%5B%5D=14950589&uids%5B%5D=1873291&uids%5B%5D=690608698&uids%5B%5D=477317922&uids%5B%5D=1464029182&uids%5B%5D=14387072&uids%5B%5D=1542516095&uids%5B%5D=1762745&uids%5B%5D=2039332008&uids%5B%5D=617459493&uids%5B%5D=863287&uids%5B%5D=594827452&uids%5B%5D=1950658&uids%5B%5D=56748733&uids%5B%5D=731556&uids%5B%5D=23269266&uids%5B%5D=1873291%20 Headers({\'host\': \'api.live.bilibili.com\', \'accept\': \'*/*\', \'accept-encoding\': \'gzip, deflate\', \'connection\': \'keep-alive\', \'user-agent\': \'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36\', \'cookie\': | [200] Headers({\'date\': \'Tue, 14 May 2024 00:16:14 GMT\', \'content-type\': \'application/json\', \'content-length\': \'143\', \'connection\': \'keep-alive\', \'bili-status-code\': \'65530\', \'bili-trace-id\': \'64cb2cb9a513a3e90ada9038056642ad:17cf32bde09505fd:ada9038056642ad:0\', \'cache-control\': \'no-cache\', \'server\': \'swoole-http-server\', \'x-bili-trace-id\': \'64cb2cb9a513a3e90ada9038056642ad:17cf32bde09505fd:ada9038056642ad:0\', \'x-envoy-upstream-service-time\': \'0\', \'vary\': \'Accept-Encoding,Origin\', \'expires\': \'Tue, 14 May 2024 00:16:13 GMT\', \'x-cache-webcdn\': \'BYPASS from blzone06\'}) {"code":65530,"msg":"route_exception","message":"route_exception","data":{"excp_code":0,"excp_msg":"Expect integer.","excp_class":"Exception"}}']
```

```05-14 08:16:44 [WARNING] nonebot_bison | API request record: https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids%5B%5D=1827139579&uids%5B%5D=666726799&uids%5B%5D=14950589&uids%5B%5D=1873291&uids%5B%5D=690608698&uids%5B%5D=477317922&uids%5B%5D=1464029182&uids%5B%5D=14387072&uids%5B%5D=1542516095&uids%5B%5D=1762745&uids%5B%5D=2039332008&uids%5B%5D=617459493&uids%5B%5D=863287&uids%5B%5D=594827452&uids%5B%5D=1950658&uids%5B%5D=56748733&uids%5B%5D=731556&uids%5B%5D=23269266&uids%5B%5D=1873291%20 Headers({'host': 'api.live.bilibili.com', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'cookie':  [200] Headers({'date': 'Tue, 14 May 2024 00:16:44 GMT', 'content-type': 'application/json', 'content-length': '143', 'connection': 'keep-alive', 'bili-status-code': '65530', 'bili-trace-id': '1ddf2d1c3b4e6dd867a9dbface6642ad:17cf32c4ddb4183b:67a9dbface6642ad:0', 'cache-control': 'no-cache', 'server': 'swoole-http-server', 'x-bili-trace-id': '1ddf2d1c3b4e6dd867a9dbface6642ad:17cf32c4ddb4183b:67a9dbface6642ad:0', 'x-envoy-upstream-service-time': '1', 'vary': 'Accept-Encoding,Origin', 'expires': 'Tue, 14 May 2024 00:16:43 GMT', 'x-cache-webcdn': 'BYPASS from blzone05'}) {"code":65530,"msg":"route_exception","message":"route_exception","data":{"excp_code":0,"excp_msg":"Expect integer.","excp_class":"Exception"}}
05-14 08:16:44 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:15], next run at: 2024-05-14 08:16:58 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 102, in exec_fetch
    to_send = await platform_obj.do_batch_fetch_new_post(sub_units)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 115, in do_batch_fetch_new_post
    return await catch_network_error(self.batch_fetch_new_post, sub_units) or []
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 53, in catch_network_error
    return await func(*args, **kwargs)
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\platform.py", line 401, in batch_fetch_new_post
    new_statuses = await self.batch_get_status([x[0] for x in sub_units])
  File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\platform\bilibili\platforms.py", line 430, in batch_get_status
    raise self.FetchError()
nonebot_bison.platform.platform.StatusChange.FetchError: ['https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?host_mid=&timezone_offset=-480&offset= Headers({\'host\': \'api.bilibili.com\', \'accept\': \'*/*\', \'accept-encoding\': \'gzip, deflate\', \'connection\': \'keep-alive\', \'user-agent\': \'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36\', \'cookie\| [200] Headers({\'date\': \'Tue, 14 May 2024 00:16:44 GMT\', \'content-type\': \'application/json; charset=utf-8\', \'transfer-encoding\': \'chunked\', \'connection\': \'keep-alive\', \'bili-status-code\': \'0\', \'bili-trace-id\': \'25fcbb4f2d6642ad\', \'cpu_usage\': \'13\', \'x-bili-trace-id\': \'18ac1b70f5d9563e25fcbb4f2d6642ad\', \'x-rid-result\': \'2\', \'content-encoding\': \'gzip\', \'expires\': \'Tue, 14 May 2024 00:16:43 GMT\', \'cache-control\': \'no-cache\', \'x-cache-webcdn\': \'BYPASS from blzone05\'}) {"count":1,"forbidden":false,"status":false}}},"type":"DYNAMIC_TYPE_AV","visible":true}],"offset":"874585122531180563","update_baseline":"","update_num":0}}', 'https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids%5B%5D=1827139579&uids%5B%5D=666726799&uids%5B%5D=14950589&uids%5B%5D=1873291&uids%5B%5D=690608698&uids%5B%5D=477317922&uids%5B%5D=1464029182&uids%5B%5D=14387072&uids%5B%5D=1542516095&uids%5B%5D=1762745&uids%5B%5D=2039332008&uids%5B%5D=617459493&uids%5B%5D=863287&uids%5B%5D=594827452&uids%5B%5D=1950658&uids%5B%5D=56748733&uids%5B%5D=731556&uids%5B%5D=23269266&uids%5B%5D=1873291%20 Headers({\'host\': \'api.live.bilibili.com\', \'accept\': \'*/*\', \'accept-encoding\': \'gzip, deflate\', \'connection\': \'keep-alive\', \'user-agent\': \'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36\', \'cookie\'| [200] Headers({\'date\': \'Tue, 14 May 2024 00:16:44 GMT\', \'content-type\': \'application/json\', \'content-length\': \'143\', \'connection\': \'keep-alive\', \'bili-status-code\': \'65530\', \'bili-trace-id\': \'1ddf2d1c3b4e6dd867a9dbface6642ad:17cf32c4ddb4183b:67a9dbface6642ad:0\', \'cache-control\': \'no-cache\', \'server\': \'swoole-http-server\', \'x-bili-trace-id\': \'1ddf2d1c3b4e6dd867a9dbface6642ad:17cf32c4ddb4183b:67a9dbface6642ad:0\', \'x-envoy-upstream-service-time\': \'1\', \'vary\': \'Accept-Encoding,Origin\', \'expires\': \'Tue, 14 May 2024 00:16:43 GMT\', \'x-cache-webcdn\': \'BYPASS from blzone05\'}) {"code":65530,"msg":"route_exception","message":"route_exception","data":{"excp_code":0,"excp_msg":"Expect integer.","excp_class":"Exception"}}']
```

```
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for arknights with interval {'seconds': 30}
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for bilibili.com with interval {'seconds': 40}
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for live.bilibili.com with interval {'seconds': 15}
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for AnonymousScheduleConfig[ff14] with interval {'seconds': 60}
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for music.163.com with interval {'minutes': 1}
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for rss with interval {'seconds': 30}
05-14 08:29:52 [INFO] nonebot_bison | register scheduler for weibo.com with interval {'seconds': 3}
```

**Comment by AzideCupric** [comment]
所用的branch看起来并不是main？

**Comment by Nenot233** [comment]
以及一个推送小bug
```B站 小可学妹
发布了新的动态： 
{"live_record_info":null,"type":1,"live_play_info":{"live_screen_type":0,"live_id":"494537236140868417","watched_show":{"num":2044,"text_small":"2044","text_large":"2044人看过","icon":"https://i0.hdslb.com/bfs/live/a725a9e61242ef44d764ac911691a7ce07f36c1d.png","icon_location":"","icon_web":"https://i0.hdslb.com/bfs/live/8d9d0f33ef8bf6f308742752d13dd0df731df19c.png","switch":true},"room_type":0,"title":"【小可】主打原生态","parent_area_name":"虚拟主播","parent_area_id":9,"room_paid_type":0,"uid":14387072,"live_s...
详情: https://t.bilibili.com/931290467632414725
```

**Comment by Nenot233** [comment]
> 所用的branch看起来并不是main？

所以是我NB的问题？

**Comment by AzideCupric** [comment]
如果你订阅了B站的直播推送，而不是B站直播的推送，就会这样（

**Comment by hakunomiko** [comment]
遇到了一样的问题，报错信息AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])以下是关注列表
B站 | 弥希Miki | 477317922 | 一般动态 专栏文章 视频 纯文字 转发
Bilibili直播 | 弥希Miki | 477317922 | 开播提醒 标题更新提醒
新浪微博 | 弥希MIKI | 7576338081 | 转发 视频 图文 文字
B站 | 千幽Chiyuu | 690608691 | 一般动态 专栏文章 视频 纯文字 转发
Bilibili直播 | 千幽Chiyuu | 690608691 | 开播提醒 标题更新提醒

**日志**
```
AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])
06-15 03:38:57 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:03], next run at: 2024-06-15 03:39:00 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 107, in exec_fetch
    to_send = await platform_obj.do_fetch_new_post(SubUnit(schedulable.target, send_userinfo_list))
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 109, in do_fetch_new_post
    return await catch_network_error(self.fetch_new_post, sub_unit) or []
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 53, in catch_network_error
    return await func(*args, **kwargs)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 396, in fetch_new_post
    return await self._handle_status_change(new_status, sub_unit)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 376, in _handle_status_change
    diff = self.compare_status(sub_unit.sub_target, old_status, new_status)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\bilibili.py", line 449, in compare_status
    match new_status.get_live_action(old_status):
AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])
```

**Comment by AzideCupric** [comment]
看看最新的 v0.9.3 还有问题吗

**Comment by Nenot233** [comment]
```08-08 16:51:18 [ERROR] uvicorn | Exception in ASGI application
﻿
Traceback (most recent call last):
File "<string>", line 15, in <module>
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
get_driver().run(*args, **kwargs)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
uvicorn.run(
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
server.run()
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
self.run_forever()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
self._run_once()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
handle._run()
File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
> File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
return await self.app(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
await super().__call__(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
await self.middleware_stack(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
raise exc
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
await self.app(scope, receive, _send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
raise exc
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
await self.middleware_stack(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 776, in app
await route.handle(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 485, in handle
await self.app(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
await super().__call__(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
await self.middleware_stack(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
raise exc
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
await self.app(scope, receive, _send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
raise exc
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
await self.middleware_stack(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 776, in app
await route.handle(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
await self.app(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 77, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
raise exc
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\starlette\routing.py", line 72, in app
response = await func(request)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\fastapi\routing.py", line 278, in app
raw_response = await run_endpoint_function(
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
return await dependant.call(**values)
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\admin_page\api.py", line 144, in get_target_name
return {"targetName": await check_sub_target(platformName, T_Target(target))}
File "D:\BOT\Nonbot2\Bison\.venv\lib\site-packages\nonebot_bison\apis.py", line 9, in check_sub_target
scheduler = scheduler_dict[scheduler_conf_class]
KeyError: <class 'nonebot_bison.platform.bilibili.scheduler.BilibiliSite'>
```
新版本添加B站用户提示这个
