### ISSUE TITLE
显示报错AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])

### ISSUE THREAD

**Issue by hakunomiko** [MountainDash/nonebot-bison#557]
## 环境

- nonebot-bison 版本：2.3.1
- nonebot 版本：v0.9.2
- 安装方式：（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装
- 操作系统：Windows 11 23H2 22631.3737

## 问题

遇到了和#539一样的问题，报错信息``` AttributeError: ("'NoneType' object has no attribute 'get_live_action'", []) ```以下是关注列表
B站 | 弥希Miki | 477317922 | 一般动态 专栏文章 视频 纯文字 转发
Bilibili直播 | 弥希Miki | 477317922 | 开播提醒 标题更新提醒
新浪微博 | 弥希MIKI | 7576338081 | 转发 视频 图文 文字
B站 | 千幽Chiyuu | 690608691 | 一般动态 专栏文章 视频 纯文字 转发
Bilibili直播 | 千幽Chiyuu | 690608691 | 开播提醒 标题更新提醒

## 日志

```
AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])
06-15 03:38:57 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:03], next run at: 2024-06-15 03:39:00 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 107, in exec_fetch
    to_send = await platform_obj.do_fetch_new_post(SubUnit(schedulable.target, send_userinfo_list))
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 109, in do_fetch_new_post
    return await catch_network_error(self.fetch_new_post, sub_unit) or []
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 53, in catch_network_error
    return await func(*args, **kwargs)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 396, in fetch_new_post
    return await self._handle_status_change(new_status, sub_unit)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\platform.py", line 376, in _handle_status_change
    diff = self.compare_status(sub_unit.sub_target, old_status, new_status)
  File "C:\Users\***\Desktop\QQbot\nonebot\***\.venv\Lib\site-packages\nonebot_bison\platform\bilibili.py", line 449, in compare_status
    match new_status.get_live_action(old_status):
AttributeError: ("'NoneType' object has no attribute 'get_live_action'", [])
```

- [ ] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [√] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
那为什么不在 #539 补充而是开一个重复的呢

**Comment by hakunomiko** [comment]
> 那为什么不在 #539 补充而是开一个重复的呢

不是特别常用Github的Issue，习惯性的就提了一个，实在抱歉

**Comment by AzideCupric** [comment]
那可以把issue关了并且把日志贴到另一个issue里

**Comment by hakunomiko** [comment]
好的
