### ISSUE TITLE
装载bison后机器人无法正常启动

### ISSUE THREAD

**Issue by enKl03B** [MountainDash/nonebot-bison#601]
## 环境

- nonebot-bison 版本：0.9.2
- nonebot 版本：
- 安装方式：（以下方式的一种或者其他方式）
- 通过 nb-cli 安装

- 操作系统：Win11 23H2

## 问题
正常安装插件后启动，console框弹出一会便直接退出，bot未成功连接到机器人
## 日志
```log
07-29 18:02:24 [SUCCESS] nonebot | NoneBot is initializing...
07-29 18:02:24 [INFO] nonebot | Current Env: prod
07-29 18:02:25 [ERROR] nonebot | Failed to import "single_session"  #这段是因为我把single_session插件删除了
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "E:\MCL\nonebot\nb03-bot\.venv\lib\site-packages\nonebot\plugin\load.py", line 149, in load_builtin_plugins
    return load_all_plugins([f"nonebot.plugins.{p}" for p in plugins], [])
  File "E:\MCL\nonebot\nb03-bot\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "E:\MCL\nonebot\nb03-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "E:\MCL\nonebot\nb03-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
>File "E:\MCL\nonebot\nb03-bot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot.plugins.single_session'
07-29 18:02:25 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
07-29 18:02:25 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_hotsearch"
07-29 18:02:25 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
07-29 18:02:25 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
07-29 18:02:25 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_emojimix"
07-29 18:02:25 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
07-29 18:02:26 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_handle"
07-29 18:02:26 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_homo_mathematician"
07-29 18:02:26 [SUCCESS] nonebot | Succeeded to load plugin "nonebot-plugin-resolver"
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
07-29 18:02:27 [INFO] nonebot_plugin_admin | 已检测到软依赖nonebot_plugin_apscheduler, 开启定时任务功能
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_admin"
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_randpic"
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
07-29 18:02:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
07-29 18:02:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_multincm"
07-29 18:02:28 [INFO] nonebot_plugin_autoreply | 加载回复配置 helprep.yaml 成功
07-29 18:02:28 [INFO] nonebot_plugin_autoreply | 加载回复配置 reply.yml 成功
07-29 18:02:28 [INFO] nonebot_plugin_autoreply | 加载回复配置完毕，成功 2 个，失败 0 个
07-29 18:02:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_autoreply"
07-29 18:02:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
07-29 18:02:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
07-29 18:02:28 [WARNING] nonebot_bison | Theme arknights requires browser, but not allowed
07-29 18:02:28 [SUCCESS] nonebot_bison | Theme arknights registered
07-29 18:02:28 [SUCCESS] nonebot_bison | Theme basic registered
07-29 18:02:28 [SUCCESS] nonebot_bison | Theme brief registered
07-29 18:02:28 [WARNING] nonebot_bison | Theme ceobecanteen requires browser, but not allowed
07-29 18:02:28 [SUCCESS] nonebot_bison | Theme ceobecanteen registered
07-29 18:02:28 [WARNING] nonebot_bison | Theme ht2i requires browser, but not allowed
07-29 18:02:28 [SUCCESS] nonebot_bison | Theme ht2i registered
07-29 18:02:29 [INFO] nonebot_bison | Nonebot Bison frontend will be running at: http://localhost:8080/bison
07-29 18:02:29 [INFO] nonebot_bison | 该页面不能被直接访问，请私聊bot 后台管理 以获取可访问地址
07-29 18:02:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_bison"
07-29 18:02:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_sparkapi"
07-29 18:02:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_animeres"
07-29 18:02:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
07-29 18:02:30 [WARNING] nonebot_plugin_memes | 表情列表解析失败，将重新生成
07-29 18:02:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
07-29 18:02:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_epicfree"
07-29 18:02:31 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordle"
07-29 18:02:31 [WARNING] nonebot | Duplicated prefix rule "/help"
07-29 18:02:31 [WARNING] nonebot | Duplicated prefix rule "/upload"
07-29 18:02:31 [WARNING] nonebot | Duplicated prefix rule "/上传"
07-29 18:02:31 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_weiweibot"
07-29 18:02:31 [SUCCESS] nonebot | Running NoneBot...
07-29 18:02:31 [INFO] uvicorn | Started server process [8284]
07-29 18:02:31 [INFO] uvicorn | Waiting for application startup.
07-29 18:02:34 [SUCCESS] nonebot | Console unmounted.
07-29 18:02:34 [WARNING] nonebot | Press Ctrl-C for Application exit
07-29 18:02:34 [INFO] nonebot_plugin_saa | pop bot Bot(type='Console', self_id='console')
```
（外显只看到这些）
- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by felinae98** [comment]
尝试搞个最小复现集合？装的插件太多了，不好说谁出的问题

**Comment by AzideCupric** [comment]
只装bison能跑吗

**Comment by enKl03B** [comment]
独立运行bison后问题成功解决，谢谢解答
