### ISSUE TITLE
[bilibili-live]B站直播订阅，下播缺少图片报错

### ISSUE THREAD

**Issue by gongfuture** [MountainDash/nonebot-bison#626]
## 环境

- nonebot-bison 版本：0.9.4
- nonebot 版本：2.3.3
- 安装方式：（以下方式的一种或者其他方式）

   通过 nb-cli 安装

- 操作系统：
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎1/‎13
操作系统内部版本	19045.4842
体验	Windows Feature Experience Pack 1000.19060.1000.0

## 问题

B站直播订阅，开播和标题更改都能正常推送，唯独下播不能正常推送

## 日志

NapCat日志
```
2024-09-22 22:28:31 [DEBUG] **Bot(259***688) | [OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"send_msg","params":{"message":[{"type":"image","data":{"file":"base64://iVBORw0KGgoAAAANSUhEUgAAAyAAAAD6CAIAAADWX7TrAAAAAXNSR0IArs4c6QAAIABJREFUeJzt3XtQU9faP/DnfYfLECfBkTAiUOVSymUOhNogiKAnVfBCR2gPHIs9glV7kGPFCzhirelb1Ioj1Iq1qEWteir2yLHiFKyXlioUC6bWgL+ApVy0EHUIjiQjDISZ/v7IhdxJYKNgv5/xD9zZ2dkJIfubtZ611v/88ccfBAAAAADM+d9nfQIAAAAAzxsELAAAAACGIWABAAAAMAwBCwAAAIBhCFgAAAAADEPAAgAAAGAYAhYAAAAAwxCwAAAAABiGgAUAAADAMAQsAAAAAIYhYAEAAAAwDAELAAAAgGEIWAAAAAAMQ8ACAAAAYBgCFgAAAADDELAAAAAAGIaABQAAAMAwBCwAAAAAhiFgAQAAADAMAQsAAACAYQhYAAAAAAxDwAIAAABgGAIWAAAAAMMQsAAAAAAYhoAFAAA...","type":null,"cache":"true","proxy":"true","timeout":null}},{"type":"text","data":{"text":"详情: https://live.bilibili.com/23***09"}},{"type":"image","data":{"file":"","type":null,"cache":"true","proxy":"true","timeout":null}}],"message_type":"group","group_id":611***274},"echo":"33"} 
2024-09-22 22:28:31 [ERROR] **Bot(259***688) | 文件消息缺少参数 {"file":"","type":null,"cache":"true","proxy":"true","timeout":null} 
2024-09-22 22:28:31 [ERROR]**Bot(259***688) | 发生错误 Error: 文件消息缺少参数
    at OneBotMsgApi.handleOb11FileLikeMessage (file:///D:/NapCat/NapCatQQ/napcat.mjs:29982:13)
    at Object.image (file:///D:/NapCat/NapCatQQ/napcat.mjs:29676:21)
    at OneBotMsgApi.createSendElements (file:///D:/NapCat/NapCatQQ/napcat.mjs:29926:64)
    at SendMsg._handle (file:///D:/NapCat/NapCatQQ/napcat.mjs:36706:85)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendMsg.websocketHandle (file:///D:/NapCat/NapCatQQ/napcat.mjs:36606:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///D:/NapCat/NapCatQQ/napcat.mjs:12792:21) 
```

NoneBot日志
```
09-22 22:28:29 [INFO] nonebot_bison | status changes bilibili-live 455***741: title='***' room_id=23***09 uid=455***741 live_time=172***186 live_status=<LiveStatus.ON: 1> area_name='其他单机' uname='***' face='https://i1.hdslb.com/bfs/face/ee63384881e3d3ed998b615eb0d6c718b9205fe5.jpg' cover='https://i0.hdslb.com/bfs/live/new_room_cover/5e1f493bc98c903e2706d9c953e69d8f296a3d3e.jpg' keyframe='https://i0.hdslb.com/bfs/live-key-frame/keyframe09222226000023868809hxo0zq.jpg' category=0 -> title='***' room_id=23***09 uid=455***741 live_time=0 live_status=<LiveStatus.OFF: 0> area_name='其他单机' uname='***' face='https://i1.hdslb.com/bfs/face/ee63384881e3d3ed998b615eb0d6c718b9205fe5.jpg' cover='https://i0.hdslb.com/bfs/live/new_room_cover/5e1f493bc98c903e2706d9c953e69d8f296a3d3e.jpg' keyframe='' category=0
09-22 22:28:29 [INFO] nonebot_bison | send to platform_type=<SupportedPlatform.qq_group: 'QQ Group'> group_id=611***274: ## Post: 26D86FCDB70 ##



来源: <Platform bilibili-live>
附加信息:
- compress: True
- title: '[下播] ***'
- images: ['']
- url: 'https://live.bilibili.com/23***09'
- nickname: '*** 其他单机'
```

- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

~话说issue模板用yml写是不是更好（）~

**Comment by AzideCupric** [comment]
下播会没有关键帧截图？好奇怪（

**Comment by AzideCupric** [comment]
> 话说issue模板用yml写是不是更好（）

yml写 是指？

**Comment by gongfuture** [comment]
> > 话说issue模板用yml写是不是更好（）
> 
> yml写 是指？

https://github.com/ZWolken/Light-Novel-Yuedu-Source/tree/main/.github/ISSUE_TEMPLATE
大概像这个样子
```yml
name: Bug Report 反馈Bug / 错误
description: 创建一个issue来报告使用的过程中发现的错误等
title: "[Bug] "
labels: ["Bug"]
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 在开始反馈前，请检查已有的issue：
      description: 如果你的问题是重复的，将不会被回复并直接关闭。
      options:
        - label: 我的问题从未被其他人提及过，且不是重复的。
          required: true
        - label: 我正在使用最新发行版的书源，没有使用过时的。

  - type: textarea
    id: bug
    attributes:
      label: 问题描述
      description: 请对您Bug/错误的现象进行清晰的描述，并尽量简短。（支持Markdown、图片、附件）
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: 复现步骤
      description: 请提供必要的复现行为的步骤。（支持Markdown、图片、附件）
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: 预期行为
      description: 请描述此bug的预期行为。（支持Markdown、图片、附件）

  - type: input
    id: legado_ver
    attributes:
      label: 阅读APP版本
      placeholder: "Example: 3.25"
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 日志Log
      description: 请提供含报错的阅读APP日志文件。
      render: shell

  - type: textarea
    id: context
    attributes:
      label: 其他信息
      description: 在这里输入任何其他相关信息。（支持Markdown、图片、附件）

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 注意事项
      description: 请注意：
      options:
        - label: 我已知晓该仓库维护者仅会在能力范围内进行Bug/错误解答修复，能力范围以外的可能不会修复。
          required: true
```
最后效果是这个样子的
![image](https://github.com/user-attachments/assets/102b8aa2-5168-44b3-9562-ce5cdeaf3e5d)

**Comment by gongfuture** [comment]
> 下播会没有关键帧截图？好奇怪（

但是下播还是有封面的，所以大概可以用封面返回？

顺便我也发现了没有做直播间封禁检测，因为我直播间昨天被封了（）

**Comment by gongfuture** [comment]
> > > > 话说issue模板用yml写是不是更好（）
> > > 
> > > 
> > > yml写 是指？
> > 
> > 
> > https://github.com/ZWolken/Light-Novel-Yuedu-Source/tree/main/.github/ISSUE_TEMPLATE
> > 大概像这个样子
> > ```yaml
> > name: Bug Report 反馈Bug / 错误
> > description: 创建一个issue来报告使用的过程中发现的错误等
> > title: "[Bug] "
> > labels: ["Bug"]
> > body:
> > 
> >   - type: checkboxes
> >     id: checklist
> >     attributes:
> >       label: 在开始反馈前，请检查已有的issue：
> >       description: 如果你的问题是重复的，将不会被回复并直接关闭。
> >       options:
> >         - label: 我的问题从未被其他人提及过，且不是重复的。
> >           required: true
> >         - label: 我正在使用最新发行版的书源，没有使用过时的。
> > 
> >   - type: textarea
> >     id: bug
> >     attributes:
> >       label: 问题描述
> >       description: 请对您Bug/错误的现象进行清晰的描述，并尽量简短。（支持Markdown、图片、附件）
> >     validations:
> >       required: true
> > 
> >   - type: textarea
> >     id: step
> >     attributes:
> >       label: 复现步骤
> >       description: 请提供必要的复现行为的步骤。（支持Markdown、图片、附件）
> >     validations:
> >       required: true
> > 
> >   - type: textarea
> >     id: behavior
> >     attributes:
> >       label: 预期行为
> >       description: 请描述此bug的预期行为。（支持Markdown、图片、附件）
> > 
> >   - type: input
> >     id: legado_ver
> >     attributes:
> >       label: 阅读APP版本
> >       placeholder: "Example: 3.25"
> >     validations:
> >       required: true
> > 
> >   - type: textarea
> >     id: log
> >     attributes:
> >       label: 日志Log
> >       description: 请提供含报错的阅读APP日志文件。
> >       render: shell
> > 
> >   - type: textarea
> >     id: context
> >     attributes:
> >       label: 其他信息
> >       description: 在这里输入任何其他相关信息。（支持Markdown、图片、附件）
> > 
> >   - type: checkboxes
> >     id: acknowledgements
> >     attributes:
> >       label: 注意事项
> >       description: 请注意：
> >       options:
> >         - label: 我已知晓该仓库维护者仅会在能力范围内进行Bug/错误解答修复，能力范围以外的可能不会修复。
> >           required: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后效果是这个样子的
> > ![image](https://private-user-images.githubusercontent.com/60888755/370266325-102b8aa2-5168-44b3-9562-ce5cdeaf3e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODUyMjMsIm5iZiI6MTcyNzE4NDkyMywicGF0aCI6Ii82MDg4ODc1NS8zNzAyNjYzMjUtMTAyYjhhYTItNTE2OC00NGIzLTk1NjItY2U1Y2RlYWYzZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEzMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjRhZjhhYWQwYmQ4MGU5NTQ4ZDg5OWIwMDlmZDZlNDM4YTFmMGFlNzlkM2U5YWQwM2M4NmNiODczZTY1NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qghpTNDfRTs3TAp6WgSGwcZhaCLk2ECTK4G1xW0z2Ss)
> 
> @felinae98

我来吧

**Comment by gongfuture** [comment]
ISSUE模板 #630
